# Generated by Django 4.0.3 on 2022-07-31 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0003_alter_category_options_alter_product_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Название')),
                ('active', models.BooleanField(default=False, verbose_name='Активна')),
                ('start_at', models.DateField(blank=True, null=True, verbose_name='Действует С')),
                ('end_at', models.DateField(blank=True, null=True, verbose_name='Действует ДО')),
                ('coupon_percent', models.PositiveSmallIntegerField(blank=True, default=0, null=True, verbose_name='Величина Скидки, %')),
                ('coupon_fixed', models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Величина Скидки, фикс.')),
                ('categories', models.ManyToManyField(blank=True, related_name='coupons', to='product.category', verbose_name='Категории')),
                ('products', models.ManyToManyField(blank=True, related_name='coupons', to='product.product', verbose_name='Продукты')),
            ],
            options={
                'verbose_name': 'Скидка',
                'verbose_name_plural': 'Скидки',
            },
        ),
    ]
