# Generated by Django 4.0.3 on 2022-07-31 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_product_is_active_alter_product_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['name'], 'verbose_name': 'Категория', 'verbose_name_plural': 'Категории'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['name'], 'verbose_name': 'Продукт', 'verbose_name_plural': 'Продукты'},
        ),
    ]
