# Generated by Django 4.0.3 on 2022-10-04 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_alter_category_options_alter_product_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='hidden_for_all',
            field=models.BooleanField(default=False, help_text='Например, когда товар пока не в продаже, а планируется только в будущем, поставить галку до тех пор, пока не будет решено начать продавать', verbose_name='Скрыт для всех (админов в тч)'),
        ),
    ]
