# Generated by Django 4.0.3 on 2022-12-22 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_additionalproperty_product_additional_property'),
    ]

    operations = [
        migrations.AlterField(
            model_name='additionalproperty',
            name='warning_message',
            field=models.TextField(blank=True, null=True, verbose_name='Текст предупреждения'),
        ),
    ]
