# Generated by Django 4.0.3 on 2022-05-27 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0003_cardnumber_alter_message_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShopSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_time', models.CharField(default='11 - 19', max_length=255, verbose_name='Время работы магазина сегодня')),
            ],
            options={
                'verbose_name': 'Настройки магазина',
                'verbose_name_plural': 'Настройки магазина',
            },
        ),
    ]
