# Generated by Django 4.0.3 on 2022-06-03 11:21

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0005_groupbotmessage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='groupbotmessage',
            options={'verbose_name': 'Групповое сообщение от бота', 'verbose_name_plural': 'Групповые сообщения от бота'},
        ),
        migrations.AddField(
            model_name='groupbotmessage',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2022, 6, 3, 11, 21, 46, 195142, tzinfo=utc), verbose_name='Дата создания'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='groupbotmessage',
            name='sent_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата последней отправки'),
        ),
        migrations.AddField(
            model_name='groupbotmessage',
            name='updated_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2022, 6, 3, 11, 21, 59, 93286, tzinfo=utc), verbose_name='Дата обновления'),
            preserve_default=False,
        ),
    ]
