# Generated by Django 4.0.3 on 2022-07-17 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0006_alter_groupbotmessage_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='is_admins_chat',
            field=models.BooleanField(default=False, verbose_name='Чат админов'),
        ),
    ]
