# Generated by Django 4.0.3 on 2022-07-20 22:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0008_alter_orderitem_in_process'),
        ('bot', '0007_chat_is_admins_chat'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'verbose_name': 'Сообщение для админов', 'verbose_name_plural': 'Сообщения для админов'},
        ),
        migrations.AddField(
            model_name='message',
            name='is_for_admins',
            field=models.BooleanField(default=False, verbose_name='Для админов'),
        ),
        migrations.AddField(
            model_name='message',
            name='message_id',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='ID сообщения в TG'),
        ),
        migrations.AddField(
            model_name='message',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='messages', to='order.order', verbose_name='Заказ'),
        ),
    ]
