# Generated by Django 4.0.3 on 2022-09-07 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0008_alter_message_options_message_is_for_admins_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'verbose_name': 'Сообщение', 'verbose_name_plural': 'Сообщения'},
        ),
        migrations.AddField(
            model_name='shopsettings',
            name='work_end',
            field=models.TimeField(blank=True, null=True, verbose_name='Время окончания работы магазина сегодня'),
        ),
        migrations.AddField(
            model_name='shopsettings',
            name='work_start',
            field=models.TimeField(blank=True, null=True, verbose_name='Время начала работы магазина сегодня'),
        ),
    ]
