# Generated by Django 4.0.3 on 2022-09-07 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0009_alter_message_options_shopsettings_work_end_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopsettings',
            name='work_time',
            field=models.CharField(default='11 - 19', editable=False, max_length=255, verbose_name='Время работы магазина сегодня'),
        ),
    ]
