# Generated by Django 4.0.3 on 2022-09-20 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0010_alter_shopsettings_work_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopsettings',
            name='enable_verification',
            field=models.BooleanField(default=False, verbose_name='Включить верификацию пользователей'),
        ),
    ]
