# Generated by Django 4.0.3 on 2022-10-07 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0011_shopsettings_enable_verification'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopsettings',
            name='disable_bot',
            field=models.BooleanField(default=False, help_text='Полностью выключить бота (не будет возможности делать заказы)', verbose_name='Выключить бота'),
        ),
    ]
