# Generated by Django 4.0.3 on 2023-05-14 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0012_shopsettings_disable_bot'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shopsettings',
            name='work_time',
        ),
        migrations.AddField(
            model_name='shopsettings',
            name='work_info_message',
            field=models.CharField(default='Время работы магазина {}', help_text='Сообщение с информацией о графике работы, отображается в самом верху сообщения от бота пользователю. Оставить скобки "{}" для вставки времени работы в нужное место сообщения', max_length=255, verbose_name='Сообщение о графике работы магазина'),
        ),
    ]
