# Generated by Django 4.0.3 on 2024-10-07 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0014_alter_shopsettings_work_info_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardnumber',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Номер телефона'),
        ),
    ]
