# Generated by Django 4.0.3 on 2024-10-07 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0015_cardnumber_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardnumber',
            name='bank_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Наименование банка'),
        ),
    ]
