# Generated by Django 4.0.3 on 2022-03-31 09:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('phone', models.CharField(blank=True, default='', max_length=30, validators=[django.core.validators.RegexValidator(message='Телефон должен состоять из цифр +-(). Введите корректный номер телефона.', regex='[0-9( )\\-+]{6,20}')], verbose_name='Контактный телефон')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
