# Generated by Django 4.0.3 on 2022-04-01 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_order_created_order_in_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='cancelled',
            field=models.BooleanField(default=False, verbose_name='Отменён'),
        ),
    ]
