# Generated by Django 4.0.3 on 2022-04-01 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_order_cancelled'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='sync',
            field=models.BooleanField(default=False, verbose_name='Синхронизирован'),
        ),
    ]
