# Generated by Django 4.0.3 on 2022-04-01 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_orderitem_sync'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='in_process',
            field=models.BooleanField(default=False, verbose_name='В процессе изменения количества'),
        ),
    ]
