# Generated by Django 4.0.3 on 2022-04-01 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_orderitem_in_process'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='count',
            field=models.IntegerField(default=0, verbose_name='Количество'),
        ),
    ]
