# Generated by Django 4.0.3 on 2022-07-31 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0009_order_shipped'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='item_sum',
            field=models.FloatField(blank=True, null=True, verbose_name='Сумма в заказе'),
        ),
        migrations.AlterField(
            model_name='order',
            name='shipped',
            field=models.BooleanField(default=False, verbose_name='Вручено'),
        ),
    ]
