# Generated by Django 4.0.3 on 2022-09-03 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0011_order_pay_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='pay_type',
            field=models.CharField(choices=[('CASH', '💰'), ('CARD', '💳')], max_length=50, null=True, verbose_name='Тип оплаты'),
        ),
    ]
